<?php

/**
 * Final Design screen registry — Figma page 0:1.
 * Source of truth for UI implementation; ignore Playground 2 and other pages.
 */
return [
    'page_id' => '0:1',
    'file_key' => 'LvecE9CMZDamnuePfRILS9',

    'sections' => [
        'login' => [
            'section_id' => '819:13156',
            'frames' => [
                '108:484' => ['name' => 'Sign in with email', 'route' => 'login', 'view' => 'auth.login'],
                '108:583' => ['name' => 'Sign in with mobile number', 'route' => 'login', 'view' => 'auth.login', 'variant' => 'mobile'],
            ],
        ],
        'signup' => [
            'section_id' => '927:5307',
            'frames' => [
                '1687:35339' => ['name' => 'Business Manager Access', 'route' => 'signup.step-1', 'view' => 'auth.signup.step-1'],
                '1687:35445' => ['name' => 'Website Requirement', 'route' => 'signup.step-2', 'view' => 'auth.signup.step-2'],
                '1687:35551' => ['name' => 'WhatsApp Business Terms', 'route' => 'signup.step-3', 'view' => 'auth.signup.step-3'],
                '1687:35657' => ['name' => 'Commerce Policy', 'route' => 'signup.step-4', 'view' => 'auth.signup.step-4'],
                '1687:35763' => ['name' => 'Business Manager Verification', 'route' => 'signup.step-5', 'view' => 'auth.signup.step-5'],
                '1687:36152' => ['name' => 'Register', 'route' => 'signup.register', 'view' => 'auth.signup.register'],
                '1687:36314' => ['name' => 'Business Details', 'route' => 'signup.register', 'view' => 'auth.signup.register', 'variant' => 'business-details'],
                '1687:36429' => ['name' => 'WhatsApp connection', 'route' => 'signup.register', 'view' => 'auth.signup.register', 'variant' => 'whatsapp'],
                '1687:36521' => ['name' => 'Successfully connected', 'route' => 'signup.register', 'view' => 'auth.signup.register', 'variant' => 'success'],
                '1687:36613' => ['name' => 'Email Confirmation', 'route' => 'signup.email', 'view' => 'auth.signup.email'],
            ],
        ],
        'dashboard' => [
            'section_id' => '819:13155',
            'frames' => [
                '798:18297' => ['name' => 'Dashboard', 'route' => 'dashboard', 'view' => 'dashboard.index'],
                '819:11501' => ['name' => 'Dashboard (full)', 'route' => 'dashboard', 'view' => 'dashboard.index'],
                '819:11824' => ['name' => 'Dashboard Analytics', 'route' => 'dashboard.analytics', 'view' => 'dashboard.analytics'],
                '819:12213' => ['name' => 'Dashboard Overview', 'route' => 'dashboard.overview', 'view' => 'dashboard.overview'],
                '819:11253' => ['name' => 'Total Recipient Logs', 'route' => 'dashboard.campaigns', 'view' => 'dashboard.campaigns'],
                '819:12438' => ['name' => 'Wallet History', 'route' => 'dashboard.wallet', 'view' => 'dashboard.wallet'],
            ],
        ],
        'inbox' => [
            'section_id' => '552:11944',
            'frames' => [
                '552:12578' => ['name' => 'Inbox', 'route' => 'inbox', 'view' => 'inbox.index'],
                '553:13343' => ['name' => 'Inbox', 'route' => 'inbox', 'view' => 'inbox.index', 'variant' => 'alt'],
                '769:11627' => ['name' => 'Inbox', 'route' => 'inbox.compose', 'view' => 'inbox.compose'],
                '769:12045' => ['name' => 'Send Templates', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'send-templates'],
                '774:11076' => ['name' => 'Send Templates', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'send-templates-alt'],
                '769:12131' => ['name' => 'Media', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'media'],
                '769:12099' => ['name' => 'Location', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'location'],
                '769:12197' => ['name' => 'Sticker', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'sticker'],
                '769:12332' => ['name' => 'Tap-to-Reply Buttons', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'tap-reply'],
                '769:12487' => ['name' => 'List of Choices', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'list-choices'],
                '769:12638' => ['name' => 'Share Many Products', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'multi-product'],
                '769:12738' => ['name' => 'Share One Product', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'single-product'],
                '769:12805' => ['name' => 'Share One Product', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'single-product-alt'],
                '769:12871' => ['name' => 'Website Button', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'website-button'],
                '769:12938' => ['name' => 'Ask a Few Questions', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'ask-questions'],
                '769:13017' => ['name' => 'Ask for Location', 'route' => 'inbox', 'view' => 'inbox.index', 'modal' => 'ask-location'],
                '769:13070' => ['name' => 'Ask for Address', 'route' => 'inbox.modals.ask-for-address', 'view' => 'inbox.modals.ask-for-address'],
                '775:11210' => ['name' => 'Send Contact', 'route' => 'inbox.modals.send-contact', 'view' => 'inbox.modals.send-contact'],
            ],
        ],
        'automation' => [
            'section_id' => '453:7787',
            'frames' => [
                '452:4781' => ['name' => 'Chatbot', 'route' => 'chatbot.index', 'view' => 'automation.chatbot'],
                '1405:35496' => ['name' => 'Chatbot', 'route' => 'chatbot.index', 'view' => 'automation.chatbot'],
                '1405:35719' => ['name' => 'Chatbot Flow', 'route' => 'automation.chatbot.flow', 'view' => 'automation.chatbot-flow'],
                '452:4996' => ['name' => 'Drip Marketing', 'route' => 'automation.drip.index', 'view' => 'automation.drip'],
                '452:5378' => ['name' => 'Drip Statistics', 'route' => 'automation.drip.statistics', 'view' => 'automation.drip-statistics'],
                '452:5525' => ['name' => 'Drip Statistics Detail', 'route' => 'automation.drip.statistics.detail', 'view' => 'automation.drip-statistics-detail'],
                '1471:35478' => ['name' => 'Drip Insights', 'route' => 'automation.drip.insights', 'view' => 'automation.drip-insights'],
                '462:5671' => ['name' => 'Drip Audience Trigger Modal', 'route' => 'automation.drip.audience', 'view' => 'automation.drip-audience', 'query' => ['modal' => 'trigger-confirm']],
                '1471:35661' => ['name' => 'Drip Audience', 'route' => 'automation.drip.audience', 'view' => 'automation.drip-audience'],
                '1471:35865' => ['name' => 'Drip Timeline', 'route' => 'automation.drip.audience-empty', 'view' => 'automation.drip-audience-empty'],
                '1471:35319' => ['name' => 'Drip Design', 'route' => 'automation.drip.design', 'view' => 'automation.drip-design'],
                '1493:13229' => ['name' => 'Drip Design Alt', 'route' => 'automation.drip.design', 'view' => 'automation.drip-design', 'variant' => 'alt'],
                '452:6509' => ['name' => 'Flows', 'route' => 'automation.flows', 'view' => 'automation.flows'],
            ],
        ],
        'templates' => [
            'section_id' => '391:4969',
            'frames' => [
                '364:3880' => ['name' => 'Templates', 'route' => 'templates.index', 'view' => 'templates.index'],
                '960:5311' => ['name' => 'Templates Message Preview', 'route' => 'templates.preview', 'view' => 'templates.preview'],
                '865:19222' => ['name' => 'Variables', 'route' => 'templates.variables', 'view' => 'templates.variables'],
                '865:19493' => ['name' => 'Create New Variable', 'route' => 'templates.variables.create', 'view' => 'templates.variables.create'],
                '391:6512' => ['name' => 'Header', 'route' => 'templates.builder.header', 'view' => 'templates.builder.header'],
                '391:6873' => ['name' => 'Body', 'route' => 'templates.builder.body', 'view' => 'templates.builder.body'],
                '391:7041' => ['name' => 'Select and Add Variable', 'route' => 'templates.builder.body', 'view' => 'templates.builder.body', 'modal' => 'add-variable'],
                '391:7381' => ['name' => 'Footer', 'route' => 'templates.builder.footer', 'view' => 'templates.builder.footer'],
                '391:7647' => ['name' => 'Buttons', 'route' => 'templates.builder.buttons', 'view' => 'templates.builder.buttons'],
                '391:7981' => ['name' => 'Submit For Approval', 'route' => 'templates.builder.submit', 'view' => 'templates.builder.submit'],
            ],
        ],
        'campaigns' => [
            'section_id' => '642:5915',
            'frames' => [
                '484:10970' => ['name' => 'Campaigns', 'route' => 'campaigns.index', 'view' => 'campaigns.index'],
                '488:12220' => ['name' => 'Campaigns Active', 'route' => 'campaigns.active', 'view' => 'campaigns.active'],
                '642:5532' => ['name' => 'Campaigns Scheduled', 'route' => 'campaigns.scheduled', 'view' => 'campaigns.scheduled'],
                '491:14966' => ['name' => 'Campaign Detail', 'route' => 'campaigns.detail', 'view' => 'campaigns.detail'],
                '487:5705' => ['name' => 'Create Step 1', 'route' => 'campaigns.create.step-1', 'view' => 'campaigns.create.step-1'],
                '619:6800' => ['name' => 'Create Step 3', 'route' => 'campaigns.create.step-3', 'view' => 'campaigns.create.step-3'],
                '619:7219' => ['name' => 'Create Step 4', 'route' => 'campaigns.create.step-4', 'view' => 'campaigns.create.step-4'],
                '636:5001' => ['name' => 'Create Step 6', 'route' => 'campaigns.create.step-6', 'view' => 'campaigns.create.step-6'],
                '924:20174' => ['name' => 'Create Step 7', 'route' => 'campaigns.create.step-6', 'view' => 'campaigns.create.step-6', 'variant' => 'step-7'],
            ],
        ],
        'audience' => [
            'section_id' => '1233:29510',
            'frames' => [
                '1233:24263' => ['name' => 'Audience', 'route' => 'audience.index', 'view' => 'audience.index'],
                '1233:24835' => ['name' => 'Overview', 'route' => 'audience.overview', 'view' => 'audience.overview'],
                '1233:24998' => ['name' => 'Subscribers', 'route' => 'audience.subscribers', 'view' => 'audience.subscribers'],
                '1233:26430' => ['name' => 'Subscribers Empty', 'route' => 'audience.subscribers.empty', 'view' => 'audience.subscribers-empty'],
                '1233:26790' => ['name' => 'Subscribers Detail', 'route' => 'audience.subscribers.detail', 'view' => 'audience.subscribers-detail'],
                '1233:27149' => ['name' => 'Subscribers Import', 'route' => 'audience.subscribers.import', 'view' => 'audience.subscribers-import'],
                '1233:25344' => ['name' => 'Segments', 'route' => 'audience.segments', 'view' => 'audience.segments'],
                '1233:25545' => ['name' => 'Forms', 'route' => 'audience.forms', 'view' => 'audience.forms'],
                '1233:25729' => ['name' => 'List Fields', 'route' => 'audience.list-fields', 'view' => 'audience.list-fields'],
                '1233:26326' => ['name' => 'Settings', 'route' => 'audience.settings', 'view' => 'audience.settings'],
            ],
        ],
        'integration' => [
            'section_id' => '546:14695',
            'frames' => [
                '546:13143' => ['name' => 'Shopify', 'route' => 'integration.index', 'view' => 'integration.index'],
                '546:13448' => ['name' => 'Shopify Scopes', 'route' => 'integration.shopify.scopes', 'view' => 'integration.shopify-scopes'],
                '546:13625' => ['name' => 'Calendly', 'route' => 'integration.calendly', 'view' => 'integration.calendly'],
                '546:13718' => ['name' => 'Calendly Connected', 'route' => 'integration.calendly.connected', 'view' => 'integration.calendly.connected'],
                '546:13837' => ['name' => 'Calendly Events', 'route' => 'integration.calendly.events', 'view' => 'integration.calendly.events'],
            ],
        ],
        'form_builder' => [
            'section_id' => '1518:36922',
            'frames' => [
                '1518:35801' => ['name' => 'Form Builder', 'route' => 'form-builder.index', 'view' => 'form-builder.index'],
                '1518:35688' => ['name' => 'Create New Form', 'route' => 'form-builder.create', 'view' => 'form-builder.create'],
                '1518:36218' => ['name' => 'Create New Form', 'route' => 'form-builder.create', 'view' => 'form-builder.create'],
            ],
        ],
        'commerce' => [
            'section_id' => '1250:25902',
            'frames' => [
                '1250:23702' => ['name' => 'Commerce', 'route' => 'commerce.index', 'view' => 'commerce.index'],
                '1250:23958' => ['name' => 'Whatsapp Orders', 'route' => 'commerce.catalog', 'view' => 'commerce.catalog'],
                '1250:24317' => ['name' => 'Payment Dashboard', 'route' => 'commerce.settings', 'view' => 'commerce.settings'],
                '1250:24762' => ['name' => 'Setup Payment Configuration', 'route' => 'commerce.product-detail', 'view' => 'commerce.product-detail'],
                '1262:11674' => ['name' => 'Create New Payment', 'route' => 'commerce.settings', 'view' => 'commerce.settings'],
                '1250:25253' => ['name' => 'Commerce Catalogues', 'route' => 'commerce.orders', 'view' => 'commerce.orders'],
                '1261:11478' => ['name' => 'Order Details', 'route' => 'commerce.orders.detail', 'view' => 'commerce.orders.detail'],
            ],
        ],
        'profile' => [
            'section_id' => '1129:17932',
            'frames' => [
                '1129:15274' => ['name' => 'My Profile', 'route' => 'profile.index', 'view' => 'profile.index'],
                '1129:15466' => ['name' => 'Integration', 'route' => 'profile.integration', 'view' => 'profile.integration'],
                '1129:17158' => ['name' => 'Modify Phone Business Profile', 'route' => 'profile.integration.connected', 'view' => 'profile.integration-connected'],
                '1129:15614' => ['name' => 'API', 'route' => 'profile.api', 'view' => 'profile.api'],
                '1129:15738' => ['name' => 'Subscription', 'route' => 'profile.subscription', 'view' => 'profile.subscription'],
                '1129:15958' => ['name' => 'Billing Information', 'route' => 'profile.subscription.billing', 'view' => 'profile.subscription.billing'],
                '1129:16173' => ['name' => 'Payment Method', 'route' => 'profile.subscription.payment', 'view' => 'profile.subscription.payment'],
                '1129:16342' => ['name' => 'Subscription Plans (Change Plan)', 'route' => 'profile.subscription.upgrade', 'view' => 'profile.subscription.upgrade'],
                '1129:16609' => ['name' => 'Data Deletion', 'route' => 'profile.data-deletion', 'view' => 'profile.data-deletion'],
                '1129:16892' => ['name' => 'Business Alerts Setup', 'route' => 'profile.alerts', 'view' => 'profile.alerts'],
            ],
            'nested' => [
                '1136:20237' => ['name' => 'My Team', 'route' => 'my-team.index', 'view' => 'my-team.index'],
                '1136:20236' => ['name' => 'My Team', 'route' => 'my-team.index', 'view' => 'my-team.index'],
                '1136:20827' => ['name' => 'My Team Create', 'route' => 'my-team.create', 'view' => 'my-team.create'],
                '1136:20978' => ['name' => 'Roles & Access', 'route' => 'my-team.roles', 'view' => 'my-team.roles'],
                '1136:21151' => ['name' => 'Roles & Access Assigned', 'route' => 'my-team.roles.assigned', 'view' => 'my-team.roles-assigned'],
                '1136:21334' => ['name' => 'Trigger Template', 'route' => 'trigger-template.index', 'view' => 'trigger-template.index'],
                '1136:21335' => ['name' => 'Intent Response Setting', 'route' => 'trigger-template.index', 'view' => 'trigger-template.index'],
                '1136:21520' => ['name' => 'Add New Trigger', 'route' => 'trigger-template.index', 'view' => 'trigger-template.index', 'query' => ['modal' => 'add-trigger']],
                '1136:22076' => ['name' => 'Tutorials', 'route' => 'tutorials.index', 'view' => 'tutorials.index'],
                '1136:22398' => ['name' => 'Tutorials', 'route' => 'tutorials.index', 'view' => 'tutorials.index'],
                '1136:22679' => ['name' => 'OpenAI Key', 'route' => 'openai-key.index', 'view' => 'openai-key.index'],
                '1136:22680' => ['name' => 'AI Bot Manager', 'route' => 'openai-key.index', 'view' => 'openai-key.index'],
                '1141:19444' => ['name' => 'Bot Readiness Analysis', 'route' => 'openai-key.index', 'view' => 'openai-key.index', 'query' => ['modal' => 'bot-analytics']],
                '1136:23237' => ['name' => 'API Settings', 'route' => 'openai-key.index', 'view' => 'openai-key.index', 'query' => ['tab' => 'api-settings']],
                '1136:23404' => ['name' => 'Knowledge Base', 'route' => 'openai-key.index', 'view' => 'openai-key.index', 'query' => ['tab' => 'knowledge-base']],
                '1136:23618' => ['name' => 'Test Bot', 'route' => 'openai-key.index', 'view' => 'openai-key.index', 'query' => ['tab' => 'test-bot']],
                '1136:23742' => ['name' => 'Usage Analytics', 'route' => 'openai-key.index', 'view' => 'openai-key.index', 'query' => ['tab' => 'usage-analytics']],
                '1136:23967' => ['name' => 'Global Settings', 'route' => 'openai-key.index', 'view' => 'openai-key.index', 'query' => ['tab' => 'global-settings']],
                '1174:8878' => ['name' => 'Add Sources', 'route' => 'openai-key.index', 'view' => 'openai-key.index', 'query' => ['tab' => 'knowledge-base', 'modal' => 'add-sources']],
                '1136:24073' => ['name' => 'Create New AI Bot', 'route' => 'openai-key.index', 'view' => 'openai-key.index', 'query' => ['modal' => 'create-bot']],
                '1136:24366' => ['name' => 'FAQs', 'route' => 'faqs.index', 'view' => 'faqs.index'],
                '1156:9368' => ['name' => 'FAQs', 'route' => 'faqs.index', 'view' => 'faqs.index'],
                '1167:11357' => ['name' => 'Webhooks', 'route' => 'webhooks.index', 'view' => 'webhooks.index'],
                '1167:11358' => ['name' => 'Webhook List', 'route' => 'webhooks.index', 'view' => 'webhooks.index'],
                '1162:9753' => ['name' => 'Webhook Logs', 'route' => 'webhooks.logs', 'view' => 'webhooks.logs'],
                '1166:10725' => ['name' => 'Webhook Log Details', 'route' => 'webhooks.logs.detail', 'view' => 'webhooks.log-detail'],
            ],
        ],
    ],
];
